minimumReleaseAgeExclude:
  - '@dg-scripts/eslint-config'
  - '@dg-scripts/stylelint-config'
  - postcss@8.5.15

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - detect-port@1.6.1
  - semver

allowBuilds:
  '@swc/core': false
  core-js: false
